
[package]
name = "concurrent_bag_of_words"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "concurrent_bag_of_words"
path = "src/main.rs"

[dependencies]
regex = "1.10.5"
indexmap = "2.2.6"
dashmap = "5.5.3"
